# Generated by Django 4.0.5 on 2022-06-17 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnableComponentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('learnablecomponentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simplifiedCoursesApp_backend_api.learnablecomponentmodel')),
                ('contents', models.TextField()),
            ],
            bases=('simplifiedCoursesApp_backend_api.learnablecomponentmodel',),
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('learnablecomponentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simplifiedCoursesApp_backend_api.learnablecomponentmodel')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            bases=('simplifiedCoursesApp_backend_api.learnablecomponentmodel',),
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=180)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseHasLearnableComponentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('engaged_learnable_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='simplifiedCoursesApp_backend_api.learnablecomponentmodel')),
                ('engaging_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplifiedCoursesApp_backend_api.coursemodel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='coursehaslearnablecomponentmodel',
            constraint=models.UniqueConstraint(fields=('engaging_course', 'engaged_learnable_component'), name='course_has_component'),
        ),
        migrations.AddConstraint(
            model_name='coursehaslearnablecomponentmodel',
            constraint=models.UniqueConstraint(fields=('engaging_course', 'order'), name='course_has_component_order'),
        ),
    ]
